"""add booking and couple tourney tables

Revision ID: 66cba79ae33b
Revises: a85b7ebf37a1
Create Date: 2024-02-02 00:11:57.389398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66cba79ae33b'
down_revision: Union[str, None] = 'a85b7ebf37a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('after_daily_booking',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('win', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.chat_id'], )
    )
    op.create_table('couple_tourney',
    sa.Column('initiator_id', sa.Integer(), nullable=False),
    sa.Column('acceptor_id', sa.Integer(), nullable=True),
    sa.Column('registered_at', sa.Date(), nullable=False),
    sa.Column('games_total', sa.Integer(), nullable=False),
    sa.Column('games_played', sa.Integer(), nullable=False),
    sa.Column('initiator_wins', sa.Integer(), nullable=False),
    sa.Column('acceptor_wins', sa.Integer(), nullable=False),
    sa.Column('is_finished', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['acceptor_id'], ['user.chat_id'], ),
    sa.ForeignKeyConstraint(['initiator_id'], ['user.chat_id'], )
    )
    op.create_index('initiator_id_registered_at_idx', 'couple_tourney', ['initiator_id', 'registered_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('initiator_id_registered_at_idx', table_name='couple_tourney')
    op.drop_table('couple_tourney')
    op.drop_table('after_daily_booking')
    # ### end Alembic commands ###
