"""alter couple tourney games_total to wins_total

Revision ID: 92cd3cf70dc9
Revises: 4ef1c6aa7f2e
Create Date: 2024-02-04 17:16:23.178609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92cd3cf70dc9'
down_revision: Union[str, None] = '4ef1c6aa7f2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('couple_tourney', sa.Column('wins_total', sa.Integer(), nullable=False))
    op.drop_column('couple_tourney', 'games_total')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('couple_tourney', sa.Column('games_total', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('couple_tourney', 'wins_total')
    # ### end Alembic commands ###
