"""add poke_ball_table

Revision ID: dca6219d6f9f
Revises: 5ed672b345f6
Create Date: 2024-02-27 00:11:04.467610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dca6219d6f9f'
down_revision: Union[str, None] = '5ed672b345f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('poky_ball',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('emoji', sa.String(length=4), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('ownership_since', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.chat_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_poky_ball_emoji'), 'poky_ball', ['emoji'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_poky_ball_emoji'), table_name='poky_ball')
    op.drop_table('poky_ball')
    # ### end Alembic commands ###
